### ISSUE TITLE
AWS SES Email Throttling

### ISSUE THREAD

**Issue by nasirkhan** [mettle/sendportal#101]
How can i set the rate limit of email sending via SES? I read the doc at https://sendportal.io/docs/email-services/aws,  it says that i have use redis for higher limit.

From my account i can send 100/s email. How can i configure this?

**Comment by JonoB** [comment]
HI @nasirkhan - we automatically retrieve your throttle limit from AWS and apply it for you

See https://github.com/mettle/sendportal-core/blob/master/src/Traits/ThrottlesSending.php for more information

**Comment by nasirkhan** [comment]
awesome. thanks.

**Comment by tungtm-unica** [comment]
How to turn off this automatic check? or configurable limit 1 fixed way?

I'm just a developer and am not authorized to access this action.

**Comment by tapsu01** [comment]
> HI @nasirkhan - we automatically retrieve your throttle limit from AWS and apply it for you
> 
> See https://github.com/mettle/sendportal-core/blob/master/src/Traits/ThrottlesSending.php for more information

It seems like each email is still being sent to AWS SES, right? Is there a way to verify and send only the maximum allowed number of emails?
