### ISSUE TITLE
Broken variable substitution for `MAIL_FROM_NAME`

### ISSUE THREAD

**Issue by wzulfikar** [mettle/sendportal#102]
I noticed the the `MAIL_FROM_NAME` was shown as `${APP_NAME}` instead of the correct app name. 

![image](https://user-images.githubusercontent.com/7823011/102028856-1096f380-3de7-11eb-9da4-e88286d70d23.png)

I checked the `.env` file that was generated by `artisan sp:setup` and it seems like the `MAIL_FROM_NAME="${APP_NAME}"` wasn't working as expected; it yields literal `${APP_NAME}` instead of substituting the value based on the previously defined `APP_NAME`.

Here's a screenshot of how my .env file looks like:
![image](https://user-images.githubusercontent.com/7823011/102029033-d8dc7b80-3de7-11eb-9524-de363d86c554.png)

**Comment by JonoB** [comment]
This is default Laravel functionality, so not sure why this didn't work for you. Perhaps your config was cached?
