### ISSUE TITLE
How to make sure all the emails have been sent

### ISSUE THREAD

**Issue by nasirkhan** [mettle/sendportal#103]
Though I have not checked, but I assume that while I press the "Send Campaign" button, it creates messages for the selected segment or for all. Then these messages sent via queue. 

If this is the steps to send a message, is there any way to confirm if all the messages has been created? I send a campaign 2 hours ago and subscriber is near 3K, but till not it only sent to a partial of those. The status of the campaign is "Sending" now and it has not been changed for 2hours.  Is there any way to force sending? on the other day, i sent more than double number of emails within 30 minutes or so. 

I need to be sure that all the mails has been sent. how can i do that?

**Comment by JonoB** [comment]
Any emails that have been actually sent will be shown in the main Messages tab.

Please check your configuration as per https://sendportal.io/docs/getting-started/configuration-and-setup#additional-configuration, and also you log files for more information.
