### ISSUE TITLE
Email headers

### ISSUE THREAD

**Issue by Sepremex** [mettle/sendportal#107]
I have implemented the SMTP option for sending emails using this [SMTP Solution](https://github.com/mettle/sendportal/issues/98#issue-757646054), I have also added some basic tracking such as open email, click links ans so on... 
What I can't find is a way to inject the UUID in the header for each email/campaign so that I can track the bounce back emails.
I see that sendportal is using a hash per message but that hash is not sent on the email headers so I can't use that, is there a way to inject the hash in the email for bounce back tracking?
If so which file do I need to modify ?

thank you.

**Comment by JonoB** [comment]
We don't support click/open tracking for SMTP

**Comment by beyondedgesg** [comment]
hello, if we want to implement email tracking using SMTP, can anyone suggest alternative approach ?
