### ISSUE TITLE
Can't composer install

### ISSUE THREAD

**Issue by arislanhaikal** [mettle/sendportal#11]
When i git clone, and running composer install, i get some problem

`Problem 1
    - The requested package mettle/sendportal-core ^1.0 exists as mettle/sendportal-core[dev-bugfix/resend-verification-email-link, dev-bugfix/top-links-click-count, dev-dependabot/npm_and_yarn/websocket-extensions-0.1.4, dev-master] but these are rejected by your constraint.`

You can help me?
Thanks

**Comment by LeonBuchner** [comment]
Same here ....

**Comment by zaherg** [comment]
For now change this line in your `composer.json` from
```
"mettle/sendportal-core": "^1.0"
```

to 

```
"mettle/sendportal-core": "dev-master"
```

this is just a small change until @mettle publish correct package version to packagist

**Comment by JonoB** [comment]
We've tagged v1.0 on `mettle/sendportal` and `mettle/sendportal-core`, so it should install fine now!
