### ISSUE TITLE
Broken pagination in /subscribers page

### ISSUE THREAD

**Issue by wzulfikar** [mettle/sendportal#113]
When I visit the **Subscribers** page at /subscribers, the pagination buttons seem to be broken. Tested in Chrome and Opera. 

I haven't noticed this bug before, maybe because the number of subscribers was low and the pagination doesn't render the buttons. And maybe, the buttons are not actually necessary because we already have the "**« Previous**" and "**Next »**" buttons?

![Screen Shot 2021-02-14 at 14 41 03](https://user-images.githubusercontent.com/7823011/107871286-1b4f3100-6edb-11eb-8a32-9f4ad90dff93.jpg)

Some context:
- Git commit:  25f7a313cf1038f86

**Comment by JonoB** [comment]
This has been fixed in v2.0.1

**Comment by wzulfikar** [comment]
Sorry just replied. Yes, it's fixed on my end too. Thanks!

![photo_2021-04-01 14 26 58](https://user-images.githubusercontent.com/7823011/113258763-f124c780-92fe-11eb-9e0c-65c5a5f96e7e.jpeg)
