### ISSUE TITLE
delete unsubscribed issue

### ISSUE THREAD

**Issue by Lucipher** [mettle/sendportal#116]
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`edm`.`message_failures`, CONSTRAINT `message_failures_message_id_foreign` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`)) (SQL: delete from `messages` where `messages`.`subscriber_id` = 2738 and `messages`.`subscriber_id` is not null order by `id` desc)

**Comment by JonoB** [comment]
This has been fixed in v2.0.1
