### ISSUE TITLE
Double Opt-In for new Subscribers

### ISSUE THREAD

**Issue by LeonBuchner** [mettle/sendportal#119]
Does this software also supports double-opt-in for new subscribers?

In the european union its mandatory and you are not allowed to send newsletter emails without double opt in. That means that every subscriber should get an email after he got added to the list with a link to confirm it. After that you are allowed to send newsetters to the user until he revokes the permission. 

Great software but I coulnd't find anything in the docs about it...

**Comment by JonoB** [comment]
See https://github.com/mettle/sendportal/issues/65
