### ISSUE TITLE
Can I install it as Package?

### ISSUE THREAD

**Issue by AEK-BKF** [mettle/sendportal#12]
First, I'd like to thank you for this great app, I really like it !

My question is, after I checked your code, it seems like you installed it as package, so could you please show us how to do that ?
I need to integrate it in my project.

Thanks.

**Comment by JonoB** [comment]
Thanks for feedback!

At the moment, its not possible to publish github.com/mettle/sendportal-core as a package to an existing application. We know that this is needed, so we're investigating ways of doing it. Stay tuned!

**Comment by AEK-BKF** [comment]
Thank you so much.
Because I think it'll be better to make it as package, so it can be integrated into any project.
We're waiting for you best.
Thank you so much again :)

**Comment by Dohxis** [comment]
SendPortal looks impressive. Looking forward to use it as a package as well 👍

**Comment by mpixelz** [comment]
Yeah.. hopefully soon! :)

**Comment by MaybachDomei** [comment]
Would be cool as a package 👍

**Comment by AEK-BKF** [comment]
Any updates here :)

**Comment by dominik-ager** [comment]
Still no news? :) Would be awesome!

**Comment by JonoB** [comment]
Sendportal can now be installed as a package - see https://sendportal.io/docs/v2/getting-started/package-installation and https://sendportal.io/docs/v2/getting-started/upgrade-guide

**Comment by AEK-BKF** [comment]
@JonoB  Thank you so much :))
