### ISSUE TITLE
APP_NAME error

### ISSUE THREAD

**Issue by HumanG33k** [mettle/sendportal#123]
ot sure it's a real bug or i guess maybe in laravel (or whatever).

When   
APP_NAME=value with space 
the space char trigger an error and lead to a white page.

For me the good way is to lead to a working state (truncate the string) and show a message telling the currently use string.

**Comment by JonoB** [comment]
This is standard Laravel behaviour. You need to enclose the `.env` variables in `"double quotes"` if there are spaces or non-alphanumeric characters
