### ISSUE TITLE
Re-send invitation to a removed user in a workspace problem

### ISSUE THREAD

**Issue by enricouniurb** [mettle/sendportal#126]
I did the following steps:

1. I logged in and I use this feature _user management -> send invitation_ versus a colleague not register in sendportal.
2. My colleague keeps the invitation by email, follows the link, and performs the registration.
3. In my panel, he appears between the current users with the active Remove button on the Right.
4. I remove the added user.
5. I re-send an invitation to the removed user but my colleague following the link get a registration error.

![image](https://user-images.githubusercontent.com/38656571/111664402-046d6880-8812-11eb-90b3-3cd3f2d74231.png)

The only solution that I found was manually removing the user from the database.

**Comment by dljfield** [comment]
@enricouniurb Users who are already signed up to the platform cannot then reregister, as they already have user accounts. 

In this case, there is an issue where users who don't have a workspace remaining cannot access any of the interface, which means that they cannot accept an invitation to any new workspaces, or create one of their own.

We are going to release a new version of SendPortal including PR #143, that has users automatically added to any workspaces they are invited to when they have already registered with SendPortal, which will solve this issue.

To resolve the issue with this particular user right now, you will need to first delete the invitation for them, and then delete the user account. You can then reinvite them to your workspace and they can reregister as before.
