### ISSUE TITLE
Not an issue but a question not in the documentation

### ISSUE THREAD

**Issue by Sepremex** [mettle/sendportal#128]
Since my last post in here I have made a few changes, nothing in the core that still the same...
I have multiple segments/lists
each list about 10K to 60K.
So, lest use the biggest list 60K...
When the emails are sent it shows the total amount 60K emails no problems, so on our second campaign for the same list, it still shows 60K when there are 4K unsubscribes shouldn't it show 56K total sent instead of 60k ?.
So, if my list has 60K subscribers but 4K  are unsubscribes, does the system send the 60K again or only 56K for the active users?

**Comment by JonoB** [comment]
The system will only send to active subscribers. Any subscribers that have unsubscribed will not receive a message.
