### ISSUE TITLE
Email never send

### ISSUE THREAD

**Issue by HumanG33k** [mettle/sendportal#129]
When i try to create a  new campagain and email they are not send. 
But test email are send. 
I use smtp conf. 

I can provide more information if needed.

**Comment by nasirkhan** [comment]
You did not mention much details about the issue, but recently some of emails are not being sent from campaigns. It starts sending emails and after a while it shows the status sending and never changes to 'sent'. There is no error in the log file as well!

https://github.com/mettle/sendportal-core/issues/118
