### ISSUE TITLE
Unable to publish vendor files

### ISSUE THREAD

**Issue by osingh152** [mettle/sendportal#13]
By running `php artisan vendor:publish --provider=Sendportal\\Base\\SendportalBaseServiceProvider`
Unable to publish vendor files.
Any idea, How can I do that?

![image](https://user-images.githubusercontent.com/29159715/84231009-e3514c00-ab0a-11ea-8a55-246990aa74b9.png)

**Comment by JonoB** [comment]
I think that this may be a windows issue with the `\\`.

Can you please try 
```
php artisan vendor:publish --provider='Sendportal\Base\SendportalBaseServiceProvider' --force` 
```
If that doesn't work, then the following should be fine:

```
php artisan vendor:publish --tag=sendportal-assets --force
php artisan vendor:publish --tag=sendportal-config --force
php artisan vendor:publish --tag=sendportal-lang --force
php artisan vendor:publish --tag=sendportal-views --force
```

**Comment by osingh152** [comment]
> I think that this may be a windows issue with the `\\`.
> 
> Can you please try
> 
> ```
> php artisan vendor:publish --provider='Sendportal\Base\SendportalBaseServiceProvider' --force` 
> ```
> 
> If that doesn't work, then the following should be fine:
> 
> ```
> php artisan vendor:publish --tag=sendportal-assets --force
> php artisan vendor:publish --tag=sendportal-config --force
> php artisan vendor:publish --tag=sendportal-lang --force
> php artisan vendor:publish --tag=sendportal-views --force
> ```

php artisan vendor:publish --tag=sendportal-assets --force
php artisan vendor:publish --tag=sendportal-config --force
php artisan vendor:publish --tag=sendportal-lang --force
php artisan vendor:publish --tag=sendportal-views --force

It' working.
Thanks for support

**Comment by Babyna212** [comment]
It's working thanks it solved my issue
