### ISSUE TITLE
Can't create encryption key during setup

### ISSUE THREAD

**Issue by tobidwest** [mettle/sendportal#134]
When trying to run `php artisan key:generate` via SSH I'm getting the following error message:

```
PHP Warning:  require(/hp/ax/af/sp/www/lists/vendor/autoload.php): failed to open stream: No such file or directory in /hp/ax/af/sp/www/lists/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/hp/ax/af/sp/www/lists/vendor/autoload.php' (include_path='.:/usr/share/php') in /hp/ax/af/sp/www/lists/artisan on line 18
```

Indeed, the directory "vendor" does not exist in the source code I downloaded from the releases page.

**Comment by tobidwest** [comment]
These are the directories/files I see:
![image](https://user-images.githubusercontent.com/61382793/113568186-584cbf80-9610-11eb-85ba-dea5e95b9ab0.png)

**Comment by JonoB** [comment]
It looks like you haven't run `composer install` yet.

Try running `composer install`, followed by `php artisan sp:install`

**Comment by tobidwest** [comment]
@JonoB Thank you for reaching back. Is there a download that's ready to go? Unfortunately, my shared hosting provider doesn't have composer installed.

**Comment by JonoB** [comment]
Should be pretty easy to install (even on shared hosting): https://getcomposer.org/doc/00-intro.md#locally
