### ISSUE TITLE
Sorting subscribers by tags?

### ISSUE THREAD

**Issue by mpixelz** [mettle/sendportal#137]
Hi,
Thanks for the great system! 
We are using the tags to determine the campaigns we need to run.. sometimes users  when importing get enrolled in multiple tags.. how can we get a list of users who are in multiple tags? as we don't want users to be in multiple tags.

either we can fetch the list of those users and remove their additional tags to make sure they are only in one.
or if we can skip users who are already in the system when importing the csv.

how can we achieve this?

**Comment by JonoB** [comment]
You'll need to handle this manually. You can use the API if you want.
