### ISSUE TITLE
[CentOS7, MariaDB/MySQL + InnoDB] New Install - Database Migration Fails 

### ISSUE THREAD

**Issue by redshiftltd** [mettle/sendportal#138]
Hi,

I'm setting up a new instance and I can't get past the ' php artisan sp:install ' database migration step.

I'm using a blank database and running MariaDB/MySQL (mysql  Ver 15.1 Distrib 10.0.38-MariaDB, for Linux (x86_64) using readline 5.1). Database connection is fine.

It looks like InnoDB has a max key length of 767 bytes but the users table has a column that exceeds that.
Is there a required database engine for Sendportal?

Error details are below:

```
There are pending database migrations. Would you like to run migrations now? (yes/no) [yes]:
> yes

 Migration table created successfully.
 Migrating: 2014_10_12_000000_create_users_table

  Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL:  alter table `users` add unique `users_email_unique`(`email`))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 


      +9 vendor frames 
  10  database/migrations/2014_10_12_000000_create_users_table.php:26
      Illuminate\Support\Facades\Facade::__callStatic()

      +18 vendor frames 
  29  app/Traits/HasSendportalMigrationHandlers.php:43
      Illuminate\Console\Command::call()
```

**Comment by JonoB** [comment]
There could be a variety of reasons for this, but usually its due to using an older version of MySQL or utf8mb4 encoding.

See https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes or https://stackoverflow.com/questions/34716683/specified-key-was-too-long-max-key-length-is-767-bytes or https://stackoverflow.com/questions/51169760/lumen-5-6-migrate-error-specified-key-was-too-long-max-key-length-is-767-bytes for some answers.

**Comment by redshiftltd** [comment]
@JonoB You were right, upgrading to MariaDB 10.5.9 got me through the migration. Thanks!
