### ISSUE TITLE
Add plaintext support

### ISSUE THREAD

**Issue by jnnkB** [mettle/sendportal#142]
It would be cool to add plaintext support as fallback. There probably should be an automatically generated version put also the option to provide your own plain text on a template and a campain level.

**Comment by JonoB** [comment]
Yes, this would be great. Happy to accept a PR. 

Options worth considering:

- `strip_tags`
- https://github.com/mtibben/html2text

Some things to investigate:

- how are `<p>` tags handled ?
- how are line breaks handled?
