### ISSUE TITLE
Hardcoded throttle config

### ISSUE THREAD

**Issue by wzulfikar** [mettle/sendportal#145]
It this throttle config supposed to hardcoded like this instead of using the value from env var (`SENDPORTAL_THROTTLE_MIDDLEWARE`)?

https://github.com/mettle/sendportal/blob/8c3e44fc3f30e49814e2ed6e06be2dd5e6c8ca10/app/Http/Kernel.php#L42-L45

**Comment by JonoB** [comment]
Sendportal does not use the throttle as specified in `sendportal/app/Http/Kernel.php`.

Instead, the `SENDPORTAL_THROTTLE_MIDDLEWARE` env var is utilised in the api routes as a middleware: https://github.com/mettle/sendportal/blob/04f8a7f7acef2f6f00a8e2a5c346c00cebff0c04/routes/api.php#L10
