### ISSUE TITLE
 Campaigns Queued

### ISSUE THREAD

**Issue by nagaraj32** [mettle/sendportal#147]
Campaigns Queued how to resolve

**Comment by harrym403** [comment]
You need to set cron job or run the scheduler manually using this command php artisan sp:campaigns:dispatch

**Comment by hlo2109** [comment]
Hello and I tried to create campaigns and execute them but it does not work for me, I executed the direct command in the console and the campaigns were activated but no mail arrived, the tests do work, but when trying to get emails with a campaign it no longer comes out


php /home/mailmerketingdes/public_html/artisan schedule:run >> /dev/null 2>&1

**Comment by efitrillo** [comment]
I have same issue on shared hosting and cron job is working

**Comment by devops-cybersapient** [comment]
when i run php artisan sp:campaigns:dispatch and it send successfully but im not recieving any mails ..why? when i clicked test it is working
