### ISSUE TITLE
Small error on the docs for MailGun webhooks

### ISSUE THREAD

**Issue by warrickbayman** [mettle/sendportal#15]
The uri for MailGun webhooks in the documentation is `/api/webhooks/mailgun`, but should be `/api/v1/webhooks/mailgun`

**From the documentation:**

The URL depends on your domain, but must end with /api/webhooks/mailgun. For example, if SendPortal is installed at https://campaigns.marketing.com, then each webhook should point to https://campaigns.marketing.com/api/webhooks/mailgun.

**Should be**

The URL depends on your domain, but must end with /api/v1/webhooks/mailgun. For example, if SendPortal is installed at https://campaigns.marketing.com, then each webhook should point to https://campaigns.marketing.com/api/v1/webhooks/mailgun.

**Comment by JonoB** [comment]
Thanks @warrickbayman, this has been fixed.

Our docs are now open source as well - https://github.com/mettle/sendportal-docs
