### ISSUE TITLE
Not sending emails

### ISSUE THREAD

**Issue by Sepremex** [mettle/sendportal#150]
Hello, until 2 weeks ago everything was working just fine, and yesterday after we put 10K emails in the job table, it start processing it, but is not sending out any emails.<br>
I have use: #php artisan queue:work but again is not sending out anything and it shows anothing in console where before it was showing when the messages are processed, now not even remove from the database job table.<br>
if I use: #php artisan queue:work --queue=sendportal-message-dispatch it shows Processing then Processed and it does remove the job from the table, but again is not sending out any emails, what could be the problem?<br>
I have testes the emails credentials and are working fine, what else could it be?<br>
I have a dedicated server with 128GB ram, 4TB SSD so power is not an issue there... <br>
The cron job also shows that the job has been done but nothing else... <br>
Thank you.

**Comment by ilkerkocatepe** [comment]
Hello,

Cold you try to use `php artisan schedule:run` command via terminal?

Regards

**Comment by Sepremex** [comment]
Yup, I did that as well and nothing happen, but is weird because,  when is about a campaign it does nothing, but if it is a simple queue mail it does work...

**Comment by JonoB** [comment]
Please make sure that you have cron job enabled and run the queues 

https://sendportal.io/docs/v2/getting-started/configuration-and-setup#additional-configuration
