### ISSUE TITLE
Create Email Service problem, not showing configuration fields

### ISSUE THREAD

**Issue by PositiveZahid** [mettle/sendportal#153]
Hello Sendportal, 

Thanks for this wonderful solution. I just tried this on my localhost and website. 

for the localhost its working fine but for website version it does not load configuration fields after clicking dropdown menu. 

![Screenshot_1](https://user-images.githubusercontent.com/6300563/119780665-ec8a2300-beeb-11eb-9b77-34dbfeedd271.png)
![Screenshot_3](https://user-images.githubusercontent.com/6300563/119780670-edbb5000-beeb-11eb-9368-dedf8b18748a.png)

Lets see the console log.

![Screenshot_4](https://user-images.githubusercontent.com/6300563/119780725-ff045c80-beeb-11eb-988b-15c4252694ae.png)

Lets see the source code
![Screenshot_5](https://user-images.githubusercontent.com/6300563/119780728-00358980-beec-11eb-9af2-724cc1ddea4f.png)

i think this should be a small tweak, i tried to solve this by changing the source code from vendor file. but failed. please help us.

**Comment by ilkerkocatepe** [comment]
Hello,

Did you check "APP_URL" in **.env** file ?

**Comment by ilkerkocatepe** [comment]
You can try forward http to https via hosting panel or htaccess file. Don't change vendor files.

Regards

**Comment by PositiveZahid** [comment]
Thanks for your time. I have set this code on top of web.php file. Magic happened.  

`URL::forceScheme('https');`

Found the solution on [https://stackoverflow.com/questions/35827062/how-to-force-laravel-project-to-use-https-for-all-routes](https://stackoverflow.com/questions/35827062/how-to-force-laravel-project-to-use-https-for-all-routes) 

![Screenshot_7](https://user-images.githubusercontent.com/6300563/120022299-0b80d600-c00e-11eb-99c3-4603fa69c7e3.png)
