### ISSUE TITLE
Campaign stucks in sending status

### ISSUE THREAD

**Issue by shimatai-mobees** [mettle/sendportal#154]
I have 140k subscribers divided into 4 lists of 35k subscribers.

Every time I try to send a campaign using AWS SES, it get stucked in sending status. If I send to a test list with 5 e-mails, the campaign is sent successfully and I got the message in that 5 e-mail accounts.

Is that a bug or do I have to set up something else?

That occurs every time I try to send to a large list.

Sometimes stuck with 600 e-mails sent and sometimes stuck with 5k e-mails sent.

**Comment by JonoB** [comment]
This should work fine, but perhaps your server is running out of memory or similar?

Can you try manually updating the `campaigns.status_id` column to `2` for the relevant campaign. The cron job should then pick up that campaign and send the remaining messages out. It will not send duplicates.
