### ISSUE TITLE
Forbidden error, temporary 503 error

### ISSUE THREAD

**Issue by mpixelz** [mettle/sendportal#155]
Hi,
Whenever i am running an email campaign, none of the links on the email works.. even my website stops working while the emails are being sent out.
As soon as the email campaign is done, everything starts to work back again but while the process in running, none of the urls in the email work not even the unsubscribe button works..
Im keep getting complaints from the visitors about it..
the error i get is "Forbidden error, temporary 503 error"

please advice.

Using digitalocean, linux server with redis config.

**Comment by willselby** [comment]
Have you tried checking the CPU and memory usage of the server while sending a campaign?
Depending on the size of your DigitalOcean droplet it may not be able to handle visitors to your site at the same time as sending a campaign.
You could consider increasing the performance of your droplet or placing SendPortal on a separate droplet, depending on how frequently you are sending campaigns.

**Comment by JonoB** [comment]
What `QUEUE_CONNECTION` are you using in your `.env` file?
