### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by Nwenn** [mettle/sendportal#158]
Hello,
I cannot install SendPortal as a package.
I follow the procedure from the page https://sendportal.io/docs/v2/getting-started/package-installation

"composer require mettle / sendportal-core" => no problem, the package appears in "vendor"

"php artisan vendor: publish --provider = Sendportal \\ Base \\ SendportalBaseServiceProvider" => error "Unable to locate publishable resources."
And the rest does not work.

Someone has the same problem ?

(sorry, my english is not fluent)

**Comment by blake-ascent** [comment]
@Nwenn Did you run 
`composer update`
After having run the composer require command?

**Comment by Nwenn** [comment]
Yes, of course.

**Comment by Nwenn** [comment]
`Alternatively, you can add the following to your composer.json file:

"mettle/sendportal-core": "^2.0"
and then run composer update to install it.`

Done and same problem.

**Comment by Aadil77** [comment]
You can use "php artisan vendor: publish" command.
You will see list of things to publish:

![listofoption](https://user-images.githubusercontent.com/20665163/127949227-1e46d216-0d83-4a9f-9605-9d657e5cd83b.png)

Select what you want to publish by giving the index number. Enter 11 to publish SendportalBaseServiceProvider.

**Comment by Nwenn** [comment]
Sendportal does not appear in the list. I guess the problem is from before.

But I only did:
"mettle / sendportal-core": "^ 2.0" in composer.json
and "composer update"
and I had no error, besides the "mettle" / "sendportal-core" folder is present and complete in the "vendor" folder
