### ISSUE TITLE
php artisan route:cache does not work

### ISSUE THREAD

**Issue by bgmastermind** [mettle/sendportal#159]
errors with 
` Unable to prepare route [logout] for serialization. Another route has already been assigned name [logout].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:217
`
Commenting out  $authRouter->get('logout', 'LoginController@logout')->name('logout');
fixes the issue.

**Comment by Pushkraj19** [comment]
yes. But admin is not responding to anything.
