### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by iamtutumo** [mettle/sendportal#160]
hello is there a WordPress plugin for sendportal

**Comment by MrGKanev** [comment]
As far as I know, there isn't one, but you can contribute and make one. :)

**Comment by ZeiadSamir** [comment]
I’m a beginner front end and I’m going to build a full responsive website for an engineering consultant but i have some questions if any one can help please 

1- Is this kind of websites needs a huge database and wordpress dashboard or that point not very important?
2- And if so , should i build the data base first or after i finish the website and host it ? 
 
* note : this website contains only one form in contact us category that's all .

I will accept any advice ♥️

**Comment by MrGKanev** [comment]
@ZeiadSamir I'm not sure how this is connected with Sendportal's maybe WordPress integration ...?
Even if we tried to help you, your questions are too broad to give you a correct answer. (example: is this PC a cool PC?) As far as I understood, you are building an informational website. (Most "consulting" websites have information about the company and what they are doing as a service + a contact form typically. ) 

1. If we guess that you are doing the same thing, the database will be small. Depending on the need of the client you can determine if the dashboard is needed or not. 
2. It doesn't matter, you can upload the database to the place it will be hosted permanantly.

Next time check the issue you are writing on, if I understood you correctly you are just spamming issues that aren't helping the project or yourself.

**Comment by ZeiadSamir** [comment]
> @ZeiadSamir I'm not sure how this is connected with Sendportal's maybe WordPress integration ...?
> 
> Even if we tried to help you, your questions are too broad to give you a correct answer. (example: is this PC a cool PC?) As far as I understood, you are building an informational website. (Most "consulting" websites have information about the company and what they are doing as a service + a contact form typically. ) 
> 
> 
> 
> 1. If we guess that you are doing the same thing, the database will be small. Depending on the need of the client you can determine if the dashboard is needed or not. 
> 
> 2. It doesn't matter, you can upload the database to the place it will be hosted permanantly.
> 
> 
> 
> Next time check the issue you are writing on, if I understood you correctly you are just spamming issues that aren't helping the project or yourself.

Your answer was helpful enough , Thanks @MrGKanev .
