### ISSUE TITLE
Dockerized installation

### ISSUE THREAD

**Issue by marcofucito** [mettle/sendportal#168]
Could I kindly ask for a dockerized installation method on the docker hub, or a DockerFile on GitHub for easier installation?
Or could it be foreseen in the future?

Thanks

**Comment by pedroetb** [comment]
Hi @marcofucito, check #21

**Comment by sayedahmadnawid** [comment]
Hi everyone, 
Is there anyone configured the docker properly. The #21 solution is not working. it throws error.
