### ISSUE TITLE
Messages not sent. Failed job with message "PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db-sendportal.messages' doesn't exist"

### ISSUE THREAD

**Issue by lucaros97** [mettle/sendportal#169]
Apparently with no-sense (maybe after update from v2.0.1 to v2.0.3) the campaign doesn't dispatch and keep the "queued" status.
I saw that all messages go in the `failed_jobs` table with this error:
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db-sendportalpsp.messages' doesn't exist in `..../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77`

Obviously the `messages` table doesn't exist, only the "sendportal_messages" exists. What's wrong?

**Comment by mahdinur** [comment]
my SMTP not sending email. But, information system success !
