### ISSUE TITLE
404 after stand-alone installation

### ISSUE THREAD

**Issue by maltitco** [mettle/sendportal#176]
I installed the stand-alone version of the application according to the instructions, but when I go to the url I get error 404

**Comment by PDijkhuizen1990** [comment]
Hi Maltitco,

I have the same issue, clean installation;
- Win 2019
- IIS
- PHP 8 x64

Created a website en pointed at the public folder, when i navigate to the url I see an redirect to; /login and after that a 404. 

Can you tell me how you solved it? 

Gr. Peter
