### ISSUE TITLE
The file must be a file of type: text/csv, Import Error

### ISSUE THREAD

**Issue by swapinvidya** [mettle/sendportal#178]
The file must be a file of type: text/csv, text/plain, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.

this error is getting when ever i try to upload any file.

**Comment by JonoB** [comment]
Make sure that the file you're trying to uploading is one of those types.

**Comment by mikerockett** [comment]
Unfortunately, this does not work – uploading a CSV file (comma-separated) results in:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/4586280/164163376-560aca58-a2fb-4dd3-bd15-21aefd53a1c7.png">

I believe it might be picking it up as a text/plain file.

**Comment by Pushkraj19** [comment]
The issue is because of PHP Version. The FAST Excel is not working properly over PHP 7.4. Just change our php version to PHP 7.4 to get it working.
