### ISSUE TITLE
SMTP mail server

### ISSUE THREAD

**Issue by ghost** [mettle/sendportal#18]
Hello,
Is it possible to use SMTP server to send emails?

**Comment by christopheg** [comment]
The 'Getting started' section on the documentation website explains how to configure SMTP.
However that doesn't seem to work. Is this part of the documentation incorrect or is there already a built-in system for sending email with SMTP?

**Comment by JonoB** [comment]
@christopheg There are 2 different email parts:

i) The internal email system used for user invites, password reminders, etc. This is for the user that are actually administering SendPortal. You can use SMTP for this.
ii) The email systems used for delivering emails to subscribers. You cannot (at the moment) use SMTP for this.

**Comment by shirazsoft** [comment]
@JonoB 
We can add tracking options in the future.
Now just we need to send email.

**Comment by noahyalla** [comment]
Having issues with configuring Mailjet

**Comment by AmandaHPrieto** [comment]
Hello ! SMTP is working now, tracking, however, is not possible. I was curious as of why ? Is it technically impossible ?
Thanks :)
