### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by PDijkhuizen1990** [mettle/sendportal#180]
Hi,

I have a fresh installed server;
- Win Server 2016 
- IIS / PHP x64

Followed all the steps
![image](https://user-images.githubusercontent.com/87334479/144014316-e1be6aaf-8ffc-4fb1-af50-dc2679515d1b.png)

Then I created a webpage in IIS, when I navigated to http://localhost, I see a redirect to /login but then I get a 404. 
The folder is the public folder in the sendportal folder. 

![image](https://user-images.githubusercontent.com/87334479/144014665-0e250067-a411-4afd-be4b-7b4d467f5047.png)

Hope someone can help me. 

ps. 

The PHPINFO does work

![image](https://user-images.githubusercontent.com/87334479/144015050-82201f67-73bb-49a3-9834-fc7bf5a05909.png)

**Comment by PDijkhuizen1990** [comment]
Just fixed the issue... I needed to import the .htaccess file trough the IIS URL Rewrite module.

BUT! Remove this line first, isn't necessary 
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

**Comment by uhlhosting** [comment]
@PDijkhuizen1990 can you show an example of your .htaccess?

**Comment by PDijkhuizen1990** [comment]
> @PDijkhuizen1990 can you show an example of your .htaccess?

It's included with the project, however I needed to convert it to IIS.
