### ISSUE TITLE
Pagination icon broken?

### ISSUE THREAD

**Issue by dv336699** [mettle/sendportal#184]
Hi, I have installed SendPortal yesterday and looks the pagination arrows are broken?
It seems that the `.h-5` and `.w-5` classes are missing from the CSS?

Happy to submit a PR but thought I'd ask first if this is a known issue or just me.

<img width="982" alt="Screenshot 2021-12-09 at 14 31 35" src="https://user-images.githubusercontent.com/930792/145415833-6a6ac8e8-ed7d-4966-82e8-ec542b9a5feb.png">

<img width="1016" alt="Screenshot 2021-12-09 at 14 32 25" src="https://user-images.githubusercontent.com/930792/145415845-24d6bd27-f9f1-477e-af18-69f403716c5b.png">

<img width="145" alt="Screenshot 2021-12-09 at 14 32 29" src="https://user-images.githubusercontent.com/930792/145415852-ef0fa32d-fbae-4997-8103-1adb5edb9534.png">

Thanks

**Comment by kowalski215** [comment]
Hi,
Having the same issue here!

**Comment by JonoB** [comment]
Did you publish the vendor files?

```
php artisan vendor:publish --provider=Sendportal\\Base\\SendportalBaseServiceProvider
```

**Comment by dv336699** [comment]
@JonoB I thought I did, so I just done it again, is there anything else I can try?
Still same results for me.

```
> php artisan vendor:publish --provider=Sendportal\\Base\\SendportalBaseServiceProvider
Copied Directory [/vendor/mettle/sendportal-core/resources/views] To [/resources/views/vendor/sendportal]
Copied Directory [/vendor/mettle/sendportal-core/resources/lang] To [/resources/lang/vendor/sendportal]
Copied Directory [/vendor/mettle/sendportal-core/public] To [/public/vendor/sendportal]
Publishing complete.

> php artisan view:clear
Compiled views cleared!

> php artisan cache:clear
Application cache cleared!
```

**Comment by JonoB** [comment]
Weird. This was an issue a long time ago. See https://github.com/mettle/sendportal/pull/117

**Comment by kowalski215** [comment]
Hi @JonoB ,
same here, just tried republishing vendor files, but still seeing the big arrow icon...

**Comment by kowalski215** [comment]
Hi. Is there any news concerning this?
Adding CSS classes for w-5 and h-5 actually fixes it

Thanks :)

**Comment by michaelzap** [comment]
Even after adding .h-5 and .w-5 rules, the pagination CSS is very messy (and wrapped in a sm-6 column)
![Screenshot from 2022-01-26 15-13-20](https://user-images.githubusercontent.com/2800260/151262995-899bd081-bb7f-429c-909c-2eb3cab77ddb.png)
.

**Comment by krognome** [comment]
Anyone who knows any CSS can fix this in a matter of minutes. If you do not know CSS then please stop developing bc you are upsetting real professionals like myself taking work away from people who care enough about their career to study CSS. Thanks :)

**Comment by d3cline** [comment]
edit 
`./public/vendor/sendportal/css/bootstrap.min.css`
add
```
.h-5 {
  height: 5rem !important;
}

.w-5 {
  width: 5rem !important;
}
```
