### ISSUE TITLE
Can it run on php 8?

### ISSUE THREAD

**Issue by diazsasak** [mettle/sendportal#186]
Hi community,

Can this run on php 8 with no problem? thanks

![image](https://user-images.githubusercontent.com/7880137/147444029-8e5373d7-6529-4c4f-a6a5-f25c8ca61734.png)

**Comment by manoaratefy** [comment]
Hello,

This seems to work correctly on PHP 8.0. I tested it and didn't found any bug on PHP 8.0. At the same time, it makes sense. Laravel is compatible with PHP 8.0.

Hope my answer will help.

**Comment by martinmildner** [comment]
Same here, works fine on PHP 8.1!

**Comment by metabinaryio** [comment]
composer install --ignore-platform-req=php

**Comment by Pushkraj19** [comment]
Yes. Close it now.
