### ISSUE TITLE
Campaign's Opens and Clicks options are not working

### ISSUE THREAD

**Issue by umerghori786** [mettle/sendportal#190]
Hi i make a campaign and send to my both of email accounts.... and when i click on email which i receive then these option are not working...
![image](https://user-images.githubusercontent.com/65702036/148938023-04296fc3-1d0e-4b07-92a8-2658a9937d1f.png)
![image](https://user-images.githubusercontent.com/65702036/148938092-3562f6a4-3fa3-4eef-8ae7-8c9da80c147b.png)
![image](https://user-images.githubusercontent.com/65702036/148938120-c5904b71-4c68-4eed-8380-e3f540ac5da6.png)

it shows nobody click on emails...
Thanks

**Comment by JonoB** [comment]
Have you set up your queue jobs and queue workers?

https://sendportal.io/docs/v2/getting-started/configuration-and-setup#additional-configuration

**Comment by umerghori786** [comment]
Yes i set it on server cron jobs you can see it
![image](https://user-images.githubusercontent.com/65702036/148943937-b01d06a6-c5b4-4b6c-af46-a54d00747938.png)
you see here send automatically option working

**Comment by JonoB** [comment]
What about your queue configuration in Laravel? See that page in the docs for "Message Sending & Queues"

**Comment by umerghori786** [comment]
Ok thanks i will see.. but send automatically option are also using queue job but this option is working

**Comment by umerghori786** [comment]
one last thing is it necessary to use redix for this?
