### ISSUE TITLE
Integration with  Oracle Cloud Email Delivery Service

### ISSUE THREAD

**Issue by mehargags** [mettle/sendportal#201]
Hi Everyone,
 Oracle Cloud Email Delivery Service has been available since 4 years now but sadly isn't much popular. I was wondering if the devs can look into the https://docs.oracle.com/en-us/iaas/Content/Email/Concepts/overview.htm and provide API integration for  Oracle Cloud Email Delivery Service as well in upcoming releases.

Many thanks

**Comment by JonoB** [comment]
PRs welcome
