### ISSUE TITLE
how to send emails with sendportal api?

### ISSUE THREAD

**Issue by rohan2734** [mettle/sendportal#205]
how to send emails with sendportal api?

i have checked the API docs but it's not available

**Comment by avantassel** [comment]
You need to create a campaign, this is nice since then you can assign a template,

https://sendportal.io/docs/v2/api/campaigns#send

**Comment by avantassel** [comment]
nevermind, I can't seem to get this working either, as this endpoint doesn't take any post data like who to send to....

**Comment by JonoB** [comment]
PR will be gladly accepted

**Comment by vipinelarafy** [comment]
there are no any clearfication
