### ISSUE TITLE
Website down when queue is processing

### ISSUE THREAD

**Issue by mpixelz** [mettle/sendportal#209]
Hi,
I have sendportal installed on a subdomain of our official website both of which are installed on a digitalocean droplet.
Whenever the campaign is running and email sending queue is processing, the website becomes unavailable. Even if someone tries to unsubscribe during that queue processing fails.
Is there anything we can do to rectify that?
Ive already tried increasing the ram and processor of the droplet but still facing the same issue.
thank you.
----
"php": "^7.3",
"laravel/framework": "^8.0",
"mettle/sendportal-core": "^2.0"

Running on DigitalOcean: Ubuntu 18.04 x64
2 vCPUs
2GB / 60GB Disk

**Comment by Pushkraj19** [comment]
looks like its too late like year but still. what do you see in logs ?

**Comment by JonoB** [comment]
It depends on how big your mailing list it. If you have a large list, put sendportal on a separate droplet so that it doesn't affect the prod website
