### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by jinjie** [mettle/sendportal#21]
Nice to have a docker image

**Comment by MathiasOliveira** [comment]
Support for this.

**Comment by wzulfikar** [comment]
Hey @jinjie, if you're still in search of a dockerized SendPortal, I made a repo that might be of your interest: https://github.com/wzulfikar/docker-sendportal. Cheers!

**Comment by jinjie** [comment]
@wzulfikar Awesome!

**Comment by JonoB** [comment]
This is amazing @wzulfikar !

Very nice :rocket:
