### ISSUE TITLE
SES track option not working

### ISSUE THREAD

**Issue by umerghori786** [mettle/sendportal#212]
Hi thanks for this free source sendportal.  but in my case click and open tracking is not working in data base is is_open_tracking and is_click_tracking is enable as you see in image.... but sent_count , open_count are not updated.. I am using QUEUE_CONNECTION=sync in database. thanks for any help

[
![image](https://user-images.githubusercontent.com/65702036/161696691-e29373ca-3dc3-4e1e-85ac-0c093dd8a461.png)
](url)

**Comment by syaiful9507** [comment]
hello, i also have problem like this. i has been setup AWS SES like sns, verify identify, user group and ses.
until now not solve.

**Comment by tungtm-unica** [comment]
**open_count** and **click_count** are not working now, get it from **unique_open_count** and **unique_click_count**

**Comment by JonoB** [comment]
Yes, `open_count` and `click_count` are not used at the moment.

`unique_open_count` and `unique_click_count` are the fields that you should use
