### ISSUE TITLE
Its nice, but no visual editor?

### ISSUE THREAD

**Issue by petrk94** [mettle/sendportal#214]
Hello,
thanks for the great tool, but I just saw, that there are not visual templates or even visual editor available.
I think this should be mentioned in the docs, because there I could not find any templates like mailchimp is offering, or at least prebuild ones, would be helpful. 

I would even like to add some contribution, there is no information about deploying it on apache with .htaccess, only with ngnix config file, so I would like to help that this code can be added to the docs for apache server user:

.htaccess

`<IfModule mod_rewrite.c>

    RewriteEngine On
    RewriteBase /

    RewriteRule ^$ public/index.php [L]

    RewriteRule ^((?!public/).*)$ public/$1 [L,NC]

</IfModule>
`

**Comment by krognome** [comment]
Took me less then 5 minutes to replace code mirror with summernote and now I have a visual editor.

**Comment by uhlhosting** [comment]
> Took me less then 5 minutes to replace code mirror with summernote and now I have a visual editor.

Share?

**Comment by JonoB** [comment]
Happy to accept PRs
