### ISSUE TITLE
Email sending is frozen

### ISSUE THREAD

**Issue by muustafacokyasar** [mettle/sendportal#216]
As you can see from the screenshot, sending the e-mail stopped in this way.  It's been this way for about 24 hours.  I am using Amazon SES.

There are no errors in the log record.

Thank you for your help.

![Screenshot_20220417-194637_Edge](https://user-images.githubusercontent.com/47488409/163724428-bd6bf953-8d62-4786-bfae-46091ed55728.jpg)

**Comment by umerghori786** [comment]
I am facing this issue also but my campaign stuck on 60 emails.. my que connection is sync and cron job runs every 30mints is it ok

**Comment by art-n** [comment]
Same through Amazon SES, any idea ?

**Comment by umerghori786** [comment]
> Same through Amazon SES, any idea ?

@art-n 
change que connection in .env QUEUE_CONNECTION=database
then your db should have jobs table..
then run this command in console php artisan queue:work --queue=sendportal-message-dispatch

**Comment by art-n** [comment]
Hey @umerghori786,

Thank you for the reply.

I've edited .env file, but I miss with "your db should have jobs table". I only have an empty "failed jobs" table.

So I've tried to run php artisan but nothing happens.

**Comment by umerghori786** [comment]
> Hey @umerghori786,
> 
> Thank you for the reply.
> 
> I've edited .env file, but I miss with "your db should have jobs table". I only have an empty "failed jobs" table.
> 
> So I've tried to run php artisan but nothing happens.
@art-n 

php artisan queue:table    this command make job table..... i think you first delete failed jobs table also before running this command
![image](https://user-images.githubusercontent.com/65702036/201978866-3bb22934-802b-4f9b-8485-70acc919a734.png)

then its works... you can ask me if you face any issue

**Comment by art-n** [comment]
Thank you for your help @umerghori786

I now have jobs table.

But for any reasons it changes sending to sent status but no more emails has been sent.

I also tried to change sent status to queued and fire php artisan command, same result.

**Comment by umerghori786** [comment]
php artisan schedule:run    do you run this command ?   bcz this command responsible to send emails in jobs table

**Comment by Pushkraj19** [comment]
In order to use the database queue driver, you will need a database table to hold the jobs. To generate a migration that creates this table, run the queue:table Artisan command. Once the migration has been created, you may migrate your database using the migrate command:

```
php artisan queue:table
 
php artisan migrate
```

Finally, don't forget to instruct your application to use the database driver by updating the QUEUE_CONNECTION variable in your application's .env file:
`
QUEUE_CONNECTION=database
`
