### ISSUE TITLE
[Feature Request] Custom fields

### ISSUE THREAD

**Issue by CodeAlDente** [mettle/sendportal#218]
It'd be great to have custom fields for subscribers, e.g. company name or some sort of individual salutation.

**Comment by mitchellkellett** [comment]
+1

This is the only thing stopping me from making the jump to SendPortal.

**Comment by saloniamatteo** [comment]
I agree. Sendportal, even if custom fields are not implemented, should implement fields like "Company name", "Phone number", and so on.

**Comment by Stuart92** [comment]
Agreed! Custom fields would be nice, but Company Name and Phone Number would make it usable.

**Comment by mohamm6d** [comment]
this is also what I am looking for

**Comment by JonoB** [comment]
Will gladly accept a PR

**Comment by saloniamatteo** [comment]
..I don't understand why @JonoB closed this:
- the issue was created in 2022
- this was closed as completed
- last commit was in 2021

**Comment by sabas** [comment]
I opened this one
https://github.com/mettle/sendportal-core/issues/184
