### ISSUE TITLE
[Feature Request] New languages & locales

### ISSUE THREAD

**Issue by saloniamatteo** [mettle/sendportal#224]
Hello everybody,
first and foremost, I would like to thank you for this beautiful piece of software. I've been using it for some time now and I noticed, in the profile page, there's an option to choose the locale, yet only English ("en") is available.

Would it be possible to implement other languages as well? I'm particularly interested in adding support for the Italian locale, so that the sendportal UI would be available in Italian as well. If needed, I can assist you in translating the various sendportal strings.

**Comment by JonoB** [comment]
Yep, this is possible. See https://github.com/mettle/sendportal-core/pull/148 for example.

**Comment by saloniamatteo** [comment]
@JonoB, how can I then add the language to Sendportal?
