### ISSUE TITLE
How do I configure Sendportal to send 1 email at a time every x minutes when processing a campaign queue?

### ISSUE THREAD

**Issue by githubcom13** [mettle/sendportal#228]
How do I configure Sendportal to send 1 email at a time every x minutes when processing a campaign queue?

**Comment by Pushkraj19** [comment]
You kind of. can edit the command file

to 

```
    /**
     * Get all queued campaigns.
     */
    protected function getQueuedCampaigns(): EloquentCollection
    {
        return Campaign::where('status_id', CampaignStatus::STATUS_QUEUED)
            ->where('scheduled_at', '<=', now())
            ->limit(1) //added limit to it
            ->get();
    }
```

in file `vendor/sendportal-core/src/Console/Commands/CampaignDispatchCommand.php`

This will limit all campaigns to send 1 email at every 1 minute.
