### ISSUE TITLE
Using sendgrid to send activities, open, click, etc. all tracking data does not work.

### ISSUE THREAD

**Issue by Hsiung-XX** [mettle/sendportal#235]
Using sendgrid to send activities, open, click, etc. all tracking data does not work.
Event Webhook has been configured on the sendgrid side, and the campaign is sent normally, and sendgrid already shows the campaign data.

All event webhooks are pointing to https://campaigns.marketing.com/api/v1/webhooks/sendgrid

Can anyone give an answer? @JonoB @aivis

**Comment by Pushkraj19** [comment]
Yes it doesn't work. and looks like we cant to anything about it :(

**Comment by JonoB** [comment]
Perhaps Sendgrid have changed how their webhooks work. Happy to accept a PR if anyone wants to dig in
