### ISSUE TITLE
SNS Notification Subsciption not working

### ISSUE THREAD

**Issue by subhajeet2107** [mettle/sendportal#24]
I am trying to subscribe to SNS notification, as described in the documentation

This is our URL: https://mailer.dezilo.com/api/v1/webhooks/aws

I have set subscription method as HTTPS, but it is stuck in **pending confirmation** for hours, i can see the POST request being set to nginx which responds with a 200, but how do i debug if it is subscribing to the url

How to enable logging for APIs ?

**Comment by JonoB** [comment]
Bit beyond what we can help with, but it looks like something is wrong or misconfigured with your API

`https://mailer.dezilo.com/api/v1/ping` should return a `200` response with `ok`
