### ISSUE TITLE
add or maintain subscribers via SQL

### ISSUE THREAD

**Issue by drjoeward** [mettle/sendportal#243]
Has anyone maintained the subscriber list directly via the db?   i looked at the table and not sure if it would be that difficult (once i know the workspace ID.)

I have a database i must maintain to ware house members from our national organization,  i receive email address changes and such directly from that system.  I want to keep the current member list in sync with subscribers using their membership ID as a key.   anyone done anything similar?   the national organization handles opt-in for us.

**Comment by JonoB** [comment]
> Looks like this project died :(

Nope, we're open to any PRs :)

**Comment by HeadStudios** [comment]
> > Looks like this project died :(
> 
> Nope, we're open to any PRs :)

Sure, I was just referring to the rate of answers to Github issues.

**Comment by Pushkraj19** [comment]
@JonoB really. Did you check pending PR?
