### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'list_db'@'localhost' (using password: NO) (SQL: select * from `users` where `email` =

### ISSUE THREAD

**Issue by A2D-Ankit-Dangi** [mettle/sendportal#249]
Illuminate\Database\QueryException
SQLSTATE[HY000] [1045] Access denied for user 'list_db'@'localhost' (using password: NO) (SQL: select * from `users` where `email` =

Migrations are successful and connection first time is established.
I am using Mariadb

**Comment by HeadStudios** [comment]
No replies :(

**Comment by Pushkraj19** [comment]
This might be issue from MariaDB please try using sqlite see if everything still works.

**Comment by JonoB** [comment]
Setting up your environment is not something that we support
