### ISSUE TITLE
Not sending emails and sent showing 0 despite having subscribers

### ISSUE THREAD

**Issue by HeadStudios** [mettle/sendportal#251]
I am having a challenge of not being able to send emails after they are queued and dispatched. I attach subscribers through tags - and testing I can see output of log files is:

[2023-02-08 01:50:05] local.INFO: Dispatching campaign id=25  
[2023-02-08 01:50:06] local.INFO: - Handling Campaign Tag id=4  
[2023-02-08 01:50:06] local.INFO: - Number of subscribers in this chunk: 2  
[2023-02-08 01:50:06] local.INFO: Saving message as draft campaign=25 subscriber=274  
[2023-02-08 01:50:06] local.INFO: Saving message as draft campaign=25 subscriber=275  
[2023-02-08 01:50:06] local.INFO: Finished dispatching campaigns 

I can also confirm I can send out test campaigns and they work.

I can also confirm the prospects are subscribed. 

However for some reason once it's dispatched it shows no one is in the recipient and the reports are empty. 

For further clarification I have created a video:
https://p147.p4.n0.cdn.getcloudapp.com/items/04uyXLdq/f137b53f-d27b-4c8a-b7ce-d18fb25b7a8a.mp4?v=9dba7816d4014ec024adfaf49b0ccb65

Any input would be much appreciated!

**Comment by JonoB** [comment]
According to your video, you have chosen the option to `Queue Draft` for the `Sending Behaviour` in your campaign. This means that the Messages are saved as draft, and you have to dispatch them manually.

Go check out Messages -> Draft

**Comment by HeadStudios** [comment]
Hi Jonty,

Thank you for your response - I have attempted to send again this time changing sending behavior to send automatically and I also confirm that the email is placed in Sent folder. Also I have confirmed the 2 people in the tags I'm sending to are subscribed. Please find video below of my workflow - appreciate your quick response and any other input, ideas or advice you could provide much appreciated. Thank you.
https://p147.p4.n0.cdn.getcloudapp.com/items/o0u9wJj7/d4537378-00a8-4953-9d31-4e0f174cbd3a.mp4?v=2aa3e04b3937886faed8bb9506d2cdba
