### ISSUE TITLE
Logic of where message bodies are stored

### ISSUE THREAD

**Issue by HeadStudios** [mettle/sendportal#252]
I'm investigated SendPortal code to troubleshoot on an issue of emails not being sent - I have found the Message class and reviewed the sendportal_messages table but I cannot find email_body - only subject. I am confused why an email body is not created for each Message model instance - any input on how this is looked up would be much appreciated. Thank you!

**Comment by JonoB** [comment]
The message body is not stored since it will be identical for every message (baring the merged variables)

**Comment by HeadStudios** [comment]
> The message body is not stored since it will be identical for every message (baring the merged variables)

Thank you!
