### ISSUE TITLE
Unable to create new subscribers (HTTP ERROR 500)

### ISSUE THREAD

**Issue by HeadStudios** [mettle/sendportal#255]
I'm getting a 

This page isn’t workingmail.rrdevours.monster is currently unable to handle this request.
HTTP ERROR 500

Chrome error when trying to create a subscriber - any ideas on what this could be?
https://p147.p4.n0.cdn.getcloudapp.com/items/xQuOrEbx/365ef4d2-4b02-44f9-8e82-34311d5a7bd1.mp4?v=fc2f9ee1a18f08426f95e6a9574d6471

**Comment by Pushkraj19** [comment]
I feel like the error is from server side and not from laravel sendportal.

Try running same on other server and check if it works.

**Comment by awjudd** [comment]
It looks like you are running it locally, you could try to put the Laravel application into debug mode to get full error messages:
```
APP_DEBUG=true
APP_ENV=local
```

This should make it so Laravel doesn't hide the errors.

**Comment by JonoB** [comment]
Setting up your environment is not something that we can support
