### ISSUE TITLE
 TypeError Argument 1 passed to Sendportal\Base\Http\Controllers\Campaigns\CampaignsController::show()

### ISSUE THREAD

**Issue by benstaf** [mettle/sendportal#257]
Hi, I would like to extend the app with a new type of campaigns (let's call it "new campaign"), accessed by a new route, called `create_new`

In the file [sendportal-core/src/Http/Controllers/Campaigns/CampaignsController.php](https://github.com/mettle/sendportal-core/blob/dfff6967fc4375fc896b280c3cc30ac8f1d6920d/src/Http/Controllers/Campaigns/CampaignsController.php),

I added:

`  public function create_new(): ...`

but when I go with the browser to /campaigns/create_new
I get the error:
` TypeError
Argument 1 passed to Sendportal\Base\Http\Controllers\Campaigns\CampaignsController::show() must be of the type int, string given`

how can I create this new route `create_new`?

**Comment by JonoB** [comment]
You have to create a new route in the `web.php` routes file
