### ISSUE TITLE
Email sent but 0 recipients

### ISSUE THREAD

**Issue by HeadStudios** [mettle/sendportal#261]
Hi, when I go to schedule my campaign and queue it - it works and is "sent" but the recipients are 0 even when I have a recipient which is tagged - any idea why would be much appreciated. Thank you!
https://share.getcloudapp.com/ApuvAXmq

**Comment by JonoB** [comment]
Do you have the queue workers running?

https://sendportal.io/docs/v2/getting-started/configuration-and-setup#additional-configuration

**Comment by MattSharp** [comment]
> Do you have the queue workers running?
> 
> https://sendportal.io/docs/v2/getting-started/configuration-and-setup#additional-configuration

queue workers are setup and running, if I send a manual test email they go through, but an actual campaign does not. They briefly stay as draft, then change to sent with 0 recipients, and mailjet has no record of them being sent

**Comment by HeadStudios** [comment]
One solution i found was replicating the sent campaign and then starting again... that worked for me.

**Comment by HeadStudios** [comment]
> I ran into this issue and learned that `schedule:run` isn't where the emails get dispatched throguh mail services, you also need to ensure `php artisan queue:work --queue=sendportal-message-dispatch` is constantly running and monitoring. Basically what @JonoB made mention of.

Thank you!
