### ISSUE TITLE
Anyone using SendPortal anymore ?

### ISSUE THREAD

**Issue by samien1** [mettle/sendportal#266]
I see the last comments are from 2 years ago ?
Getting stuck and looking for an alternative to SendPortal
Impossible to implement Opens and Click tracking
Appreciate

**Comment by mikkivirus-dev** [comment]
Is it still working Guys

**Comment by bendaoua** [comment]
I don't think so. Sould not make it work
3h spent debugging it - no luck

**Comment by HeadStudios** [comment]
Yeh it seems support is DEAD :( which sucks

**Comment by benstaf** [comment]
I am preparing a fork with more advanced features.

**Comment by b0rt** [comment]
i recently installed it and its working great, excpet som minor details like https://github.com/mettle/sendportal/issues/270

**Comment by benstaf** [comment]
@drraccoony are you using Redis ? With sync the sending process randomly crashes after a few hundred emails sent

**Comment by JonoB** [comment]
@benstaf - I'm not surprised if its crashing with `sync`. Read the [docs here](https://sendportal.io/docs/v2/getting-started/configuration-and-setup#additional-configuration), specifically:

> However, as this [i.e. sync method] does not scale well, this approach is only recommended for relatively small message sending requirements.

**Comment by HeadStudios** [comment]
> We recently started Sendportal using instead of Magento, and its been great. We had to make some changes to get it to sync with our customers from "Bagisto" and no issues. We're sending upwards of 450k emails a month.

Wow that's awesome! And gives me a lot of confidence in using it going forward.

**Comment by HeadStudios** [comment]
I am using it and I love it! Just wish there was a bit more support on the Github but can't expect high top support for a free product I guess. The community is a bit lacking but the software itself is very good and no complaints here.

**Comment by HeadStudios** [comment]
> I am preparing a fork with more advanced features.

Did you ever the fork running @b0rt ?
