### ISSUE TITLE
Email stuck 

### ISSUE THREAD

**Issue by HeadStudios** [mettle/sendportal#269]
Hi,

My emails are stuck and I don't know why:
https://share.getcloudapp.com/Qwu88gqv

Any idea on what I can do to ensure the email gets sent?

It just says sending 179 of 180 

Thank you!

**Comment by tahseenjamal** [comment]
@HeadStudios Is your issue resolved ?

**Comment by HeadStudios** [comment]
Hi! Yes it has - thank you so much for following up :) - closing issue now.
