### ISSUE TITLE
Elascticemail integration

### ISSUE THREAD

**Issue by neo22s** [mettle/sendportal#28]
I think it's the cheapest transactional email in the market 

https://github.com/ElasticEmail/ElasticEmail.WebApiClient-php

https://elasticemail.com/api-pricing

**Comment by joshuafranks** [comment]
There's already [an open PR](https://github.com/mettle/sendportal-core/pull/24) which adds support for ElasticEmail; we'll be reviewing it internally tomorrow.

**Comment by neo22s** [comment]
congrats guys!!
