### ISSUE TITLE
New Updates

### ISSUE THREAD

**Issue by faridalizade** [mettle/sendportal#293]
Hello guys,

Can you please let me know how to update new necessary updates for SendPortal and SendPortal-Core using Terminal?

Because I see here SendPortal 3.0.1 and SendPortal Core 3.0.0, but I do not know how to update mine. I use SendPortal v2.

Thank you for your support newbies.

**Comment by JonoB** [comment]
You should be ok to just update composer with the new package version. There are no database migrations, schema changes or anything like that
