### ISSUE TITLE
Unsubscribe link

### ISSUE THREAD

**Issue by wendellwva** [mettle/sendportal#297]
Hello! I have a small problem with the unsubscribe link. When I use the placeholder {{unsubscribe_url}} it generates a valid link, but with http://localhost/ before the link. Does anyone know how to solve it?

like this: http://localhost/app.mydomain.org/subscriptions/unsubscribe/ec3df930-93e6-4d37-a364-9c8011336afd

Thanks in advance

**Comment by noehmeier** [comment]
Did you change in `.env` file the property `APP_URL` from localhost to your domain base url?

See https://sendportal.io/docs/v2/getting-started/configuration-and-setup#manual-configuration &rarr; Base URL

**Comment by wendellwva** [comment]
That's right my friend. I had put the domain but without the https://

thanks.
