### ISSUE TITLE
Doesnt let me add smtp mail

### ISSUE THREAD

**Issue by Skeid9** [mettle/sendportal#307]
The SMTP Email Service requires you to enter a host
    The SMTP Email Service requires you to enter a port

the values are set inside the .env and it also takes them correctly, tested to get them from the web app..

How can i fix this?

**Comment by cod1ingcoding** [comment]
if you use cdn https => http model, This will be the case.

**Comment by Skeid9** [comment]
Fixed but now I run a campaign and its stuck as "queued".

I have installed redis and tried php artisan queue:work and the horizon command but nothing.

How to fix?
