### ISSUE TITLE
Error: String data, right truncated: 1406 Data too long for column 'content'

### ISSUE THREAD

**Issue by nea** [mettle/sendportal#31]
Hi there

I am currently testing Sendportal as it fits to awesome use cases. I just created my first test campaign and was adding content, also a picture. The picture was pasted into the `content` field to be inserted into the DB. But as a pretty long base64 string such as 

```
<img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAUDBAoJCQcFBQgICAcHBgcIBwgICAcFBwgHBwcHBwcFBwcHChALBwgOCQcHDBUMDhERExMTBwsWGBYSGBASExIBBQUFCAcIDQgIDRIMDAwSEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEv/AABEIAtAFAAMBIgACEQEDEQH/xAAdAAACAgMBAQEAAAAAAAAAAAAAAwIEBQYHAQgJ/8QAZRAAAQMCAgQGDQgECQkGBQEJAgADBAESBRMGESIyFCMzQlJyBxUhMUNTYnOCg5KTsyQ0UWFjo8PTCBZBokRUdLK0wtLj8CU1ZHF1gYSUpBc2teLy80VVkaHEZbHUJoXR5JWlxf/EABsBAQEBAQEBAQEAAAAAAAAAAAACAwEEBQYH/8QANxEBAQACAAUDBAEDAwMCBwEAAAIDEgEEEyIyBRFCFCExUkEVI2IzUXEGcoFDYYKRoaKx4fA0/9oADAMBAAIRAxEAPwDoCl+wi6Kiub6caYmVXIkI8sOkPFmpU3LF2CNxi2muwNpWnyI2coFwt1hxy3aqXSI+cmBB6Rj7N6icc+yXZO1mrn/uqQw6DXapX2lx/gLf0nVS4KFN0NfWXp2HZssNWyI0UrS5o+yuNh3N3udVH+9NlO0DEMq97UmcE+tcTUU2NnbmIfcu7qY1DbCt1q4aOpSaBTsbO6D/AKlJcJQq2NndVD9i4ao/tTZNdzu6h+xcLUlOxTuSmuFKOpNlT4u7WfVX2UyL3lwnWoqU07w53km3nLh6mtNku4koiGtcLUhTYd2JunTpXqpZNfXT0lw+3e8pMYdILcoqjbzhLKU7Up3VC0LRfTYdRNYqVtu47a65d9i7lLOFpnB/jGv1Uj8tZqbCha5+ucLmv67fIkflpn64wedJ1XfZSPy0cbk1yLPXNC1t3S+KDEV1p64b3xIcqR4zzalE04gOV5el
```

it lead to the SQLError of `SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1 (SQL: insert into `campaigns` (`name`, `subject`, `from_name`, `from_email`, `email_service_id`, `template_id`, `content`, `is_open_tracking`, `is_click_tracking`, `workspace_id`, `updated_at`, `created_at`) values ...` because of the limitation of 65535 characters for the `content` field in my plain migrated MySQL table. 

Is it possible to change that field to a `->longtext(...)` instead as I belief that content in campaigns may potentially have at least one not templated image in case of advertisements etc.

Or if you have other suggestions, I would be happy to get your feedback ^^

Thanks a lot and Best

**Comment by JonoB** [comment]
Thanks for reporting @nea, the fix will be included in the next release!

**Comment by JonoB** [comment]
This has been fixed in 1.0.2

**Comment by faridalizade** [comment]
Hello,

I newly installed SendPortal. Great work.

I also experienced the same issue with base64. Nothing helped. Can you please help me to fix it?

Thank you.

**Comment by faridalizade** [comment]
Hello,

I still experiencing the same issue on mobile.

Thanks
