### ISSUE TITLE
Email Subscriber Box Template

### ISSUE THREAD

**Issue by evanspy1** [mettle/sendportal#34]
Just a suggestion, maybe build a template in a verity of languages (JS, PHP, Node, etc.) for how to build a box where users can subscribe to the newsletter.

I want to use SendPortal, and I am probably just going to cobble together some PHP to send a post request, but it would be handy to have a snippet to show how it is supposed to be done, at the very least.  Just looking at the docs, it looks like the API requires authentication, it would be fantastic if there was a way to not require auth on certain methods so there could be simple frontend forms (using JS when I can't be bothered to make a PHP file) for just adding users.  I just want to build a little box in the bottom corner of my site letting users subscribe, and it looks like I am unfortunately going to have to build backend logic to do that.

Thanks, if this seems like something worth doing and someone has a good idea on how to implement it (what exact steps should be done), I am more than happy to contribute with code.

**Comment by JonoB** [comment]
The way that we have handled this internally is to have a form post to a controller, and then the controller does an API request to SendPortal.

Something like this:

```
public function index(Request $request)
{
    $request->validate([
        'email' => 'required|email',
    ]);

    $email = $request->get('email');

    try
    {
        $this->sendRequest($email);

        return response()->json([
            'success' => true,
        ]);
    }
    catch (\Exception $e)
    {
        \Log::error ($e);

        return response()->json([
            'success' => false,
        ]);
    }
}

protected function sendRequest($email)
{
    $client = new GuzzleHttp\Client();

    $response = $client->post('https://sendportal.example.com/api/v1/workspaces/1/subscribers', [
        'form_params' => [
            'email' => $email,
        ],
        'headers' => [
            'Authorization' => 'Bearer api-token-goes-here',
        ]
    ]);

    \Log::info($email . ' - ' . (string)$response->getStatusCode()  . ' ' . (string)$response->getBody());
}
```

**Comment by evanspy1** [comment]
Ok that makes sense.  Thanks!
