### ISSUE TITLE
The Mix manifest does not exist.

### ISSUE THREAD

**Issue by djphaser** [mettle/sendportal#36]
Hello, 

after deploying on shared hosting, the following writes to me:

The Mix manifest does not exist. (View: /www/.../sendportal/vendor/mettle/sendportal-core/resources/views/layouts/app.blade.php)

I'm sorry, I'm a beginner. Can you please tell me what's wrong? Thx.

**Comment by dsalcedo** [comment]
Read this part of SendPortal docs https://sendportal.io/docs/getting-started/configuration-and-setup

**Comment by Revarh** [comment]
@dsalcedo I keep reading and I don't see how to fix this error I also have...

**Comment by subhojit-axl** [comment]
as per the link, execute `php artisan sp:install`. It builds the FE assets.
