### ISSUE TITLE
Error when trying delete template with related campaigns

### ISSUE THREAD

**Issue by LocalHeroPro** [mettle/sendportal#45]
![image](https://user-images.githubusercontent.com/42643563/84924206-7f112800-b0c8-11ea-95fe-05ff7d941264.png)

**Comment by JonoB** [comment]
We need to add functionality to prevent deleting of templates when it has been used. Recommend to use a `DeleteTemplateRequest` that resolves the validation requirements.

**Comment by LocalHeroPro** [comment]
I only clicking and debugging and providing four you a clue what your organization have to fixing ;)

**Comment by JonoB** [comment]
This has been fixed in https://github.com/mettle/sendportal-core/pull/37
