### ISSUE TITLE
Sendgrid + test email failed (MergeContent line 70)

### ISSUE THREAD

**Issue by fserrano88** [mettle/sendportal#47]
Hi everyone,

I was trying to configure sendportal with SendGrid. After generating the sendgrid api key and adding the email service, I tried to send a test email, but it gave me the following error. 

"TypeError
Argument 1 passed to Sendportal\Base\Services\Content\MergeContent::mergeContent() must be of the type string, null given, called in /path/sendportal/src/vendor/mettle/sendportal-core/src/Services/Content/MergeContent.php on line 70" 

![Screen Shot 2020-06-19 at 00 06 28](https://user-images.githubusercontent.com/1197662/85096018-148fe300-b1c1-11ea-8b3d-322b523bf002.png)

I don't know what could have been missing and I would like to see if you can help me. Thank you

**Comment by fserrano88** [comment]
I found the problem. 

It was because I didn't write a "content". I assumed that the template was enough for a first test. I think better error handling is missing or pointing the field as required to avoid this problem. I hope it helps to be able to reduce uncontrolled errors.

Thank you

**Comment by JonoB** [comment]
This has been fixed in https://github.com/mettle/sendportal-core/pull/34
