### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by asilvabe** [mettle/sendportal#48]
Hi 👋

I am not sure if this is the right place to ask this question, if it is not, I apologize in advance.  

What happens is that I don't see I see the project code in the repository, I can only see a blank Laravel project.  I am doing something wrong?  

Thank you very much

**Comment by JonoB** [comment]
If you take a look in composer.json, you will see a reference to `sendportal-core`, which points to https://github.com/mettle/sendportal-core

Hope that helps!
