### ISSUE TITLE
Suggestions: Schedule between times?

### ISSUE THREAD

**Issue by mpixelz** [mettle/sendportal#49]
Hi,
First of all, thank you so much for this great tool. Im currently testing things out here and there to see if we can use this as our primary email sending option.

Just wanted to ask if its possible to have a queue time allocation? for instance, we send out emails offering our services to people who work 9 to 5 jobs.. and if the emails they receive is not between office hours, our conversions drop significantly.

i know you can schedule the date and time to start the campaigns, but is it possible to have a cut of time too? like send queued emails between 9am to 5pm.. and skip weekends?

i hope im making sense here.
Thanks.

**Comment by JonoB** [comment]
This is an interesting one. Its not natively possible at the moment, but there are 2 options that may work:

1. Change the `CampaignDispatchCommand` to only run between your scheduled times. At the moment, it runs every minute, but you could change it to only run between your scheduled hours

```
// old
$schedule->command(CampaignDispatchCommand::class)->everyMinute()->withoutOverlapping();

// new
$schedule->command(CampaignDispatchCommand::class)
->everyMinute()
->weekdays()
->between('9:00', '17:00')
->withoutOverlapping();
```

Of course if you have a very large campaign, then it may take some time to dispatch all of the items, and it could exceed this timeframe.

2. The other option is to only run your queue workers during the above times. I'm not sure off the top of my head how to automate that, but you would only run `php artisan horizon` during your time frames.

**Comment by mpixelz** [comment]
Hi,
how to overwrite the schedule command? 
in my app/console/kernal.php there is no default (old) commands available. sorry if i sound like a noob because maybe i am :S

**Comment by JonoB** [comment]
Actually, its not possible at the moment to do this.

However, I'm not really sure what you are trying to achieve here, because the `CampaignDispatchCommand` will only be run when you actually Send the campaign in the UI. So why not just make sure that you only click the Send button between those hours?

Alternatively, you could your actual cron job to only run between those hours, but of course that would affect all scheduled jobs.

```
* * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1
changes to 
* 9-17 * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1
```

**Comment by mpixelz** [comment]
Basically we send out around 100,000 emails every week and our audience only check their emails on weekdays 9am to 5pm. As per our previous records emails sent during those times gets better conversions. So i would like to send email during those times. 
Do we need cron even when using redis? And is there a way to do this via schedule commands instead of cron jobs?
Im using laravel forge on digitalocean ubuntu server so setting schedule is easier.

**Comment by JonoB** [comment]
Its not possible at the moment.

However, if you have enough queue workers, then sending 100,000 emails is not a lot, and can be easily dispatched between those times if you start the campaign early enough in the day.
