### ISSUE TITLE
API for campaign creation ?

### ISSUE THREAD

**Issue by dircm** [mettle/sendportal#51]
Feature request:

I can’t see any exposed API to create a campaign and then a subsequent send.

Is there a way around this currently ?  I’d like to be able to programmatically trigger the construction of a campaign with a stored template and then send to a pre defined segment.

Thanks Tom

**Comment by JonoB** [comment]
Not at the moment - happy to accept a PR

**Comment by dircm** [comment]
Ok thanks may take awhile.  Any guidance towards the campaign creation logic would be appreciated !
