### ISSUE TITLE
Showing Campaign Status as queue

### ISSUE THREAD

**Issue by varundeva** [mettle/sendportal#52]
Hello
I Installed in AWS EC2. showing sending status as Queue.
Its not changing. test email sending. but campaign not sending

**Comment by varundeva** [comment]
I tried by executing **`php artisan sp:campaigns:dispatch`** 
then all campaigns sent.
Each time i need to execute that? 
changed connection to redis in .env
still same problem


btw im not executing php artisan serve command. directly i can login through /public folder through public ip

**Comment by JonoB** [comment]
There are 2 things to check:

1. Have you set up a cron job? See `Cron Jobs` in https://sendportal.io/docs/getting-started/configuration-and-setup

2.  If you are using a redis queue connection, then you should use Horizon to handle all of your queues. Please see `Running Redis Queues With Laravel Horizon` on https://sendportal.io/docs/getting-started/configuration-and-setup

**Comment by Yuniverse-tech** [comment]
I reopen this ticket because the problem still persists despite a configuration with horizon and supervisor. All the scheduled sendings do not work and the status "queue" is still there and no message received! Sending in test mode works wonderfully against.
