### ISSUE TITLE
SNS Notification Subscription not working

### ISSUE THREAD

**Issue by mpixelz** [mettle/sendportal#54]
Hi,
Facing an exact issue as #24 

`api/v1/ping` sending a `200` response with `ok` message.

its been few hours and still stuck at pending confirmation. any help?
Thanks.

**Comment by JonoB** [comment]
Hi,

Can you please check your log files.

According to https://github.com/mettle/sendportal-core/blob/8bf2b1e20819bb7020f65c9a15a8b45142b5846c/src/Listeners/Webhooks/HandleSesWebhook.php#L37, there should be a `subscribing` entry in the log file at some point after you set up SNS.

**Comment by mpixelz** [comment]
It was an issue with my connection.. i had database as connection without the tables.. now have moved to redis.. and it got confirmed. Thanks for pointing out the log file 👍 
i wish there was some kind of video tutorial on the whole setup, configuration and running sendportal using ses, on digitalocean with laravel forge.. but i think i'll have to learn and test at the same time :)
