### ISSUE TITLE
Unable to get Amazon SNS open/click tracking working.

### ISSUE THREAD

**Issue by keenminded** [mettle/sendportal#55]
Hello!

Thanks for producing this software package and open-sourcing it! 

We have followed the documentation and have delivery with Amazon SES. Everything works except for open and click tracking. I have personally been through all of the configurations at least three times, with everything confirmed on the Amazon side. The webhooks appear to be working correctly as well, and all the SNS notifications are received based on the log entries. However, the database records for message click and open counts are not updating from the API. Currently looking through the code, but any immediate ideas will be much appreciated.

Many thanks in advance.

**Comment by keenminded** [comment]
![Screen Shot 2020-07-20 at 11 41 36](https://user-images.githubusercontent.com/4564549/87963304-1da0f800-ca7e-11ea-833e-f6852953653f.png)

Here is a screenshot from Horizon as well. All and click counts are at 0 in the database for every message.

**Comment by JonoB** [comment]
Can you confirm that open and click tracking are enabled for your campaign?

If you're able to check in the database, is `is_open_tracking` and `is_click_tracking` enabled for your campaign in the `campaigns` table?

**Comment by keenminded** [comment]
@JonoB Hi there. Yes, they are.

![Screen Shot 2020-07-20 at 16 40 20](https://user-images.githubusercontent.com/4564549/87989877-72596880-caa8-11ea-8cf5-2cabe2b1e3f8.png)

**Comment by JonoB** [comment]
@keenminded  Can you please updated `sendportal-core` to `1..0.4` and try again.

**Comment by keenminded** [comment]
@JonoB just upgraded through composer up, then performed composer dump, followed by artisan clear-compiled, and cleared all individual caches. Still nothing, I am afraid.

**Comment by JonoB** [comment]
@keenminded One more thing - did you restart your queue workers / supervisor?

**Comment by keenminded** [comment]
@JonoB No, let me try that. BRB.

**Comment by keenminded** [comment]
Yes! That did it. Thank you, @JonoB! Keep up the great work.

![Screen Shot 2020-07-21 at 11 48 02](https://user-images.githubusercontent.com/4564549/88082952-0dede600-cb48-11ea-9189-9507b05d0af5.png)

**Comment by keenminded** [comment]
@JonoB I was a little too quick to close this. I was looking at the DB records, and while the numbers are showing on the front end I'm guessing from the messages table, the numbers on the campaigns table didn't change. Is this normal?

![Screen Shot 2020-07-21 at 11 54 33](https://user-images.githubusercontent.com/4564549/88084127-8dc88000-cb49-11ea-9deb-62654a7c2229.png)

**Comment by JonoB** [comment]
@keenminded - I think those fields are deprecated, and will be removed in a future release.

Glad you got it working! :rocket:

**Comment by keenminded** [comment]
Thank you for your help, @JonoB.

**Comment by mpixelz** [comment]
Hi. 
I am using the latest version but still facing the same issue. Tried all the methods suggested but still stats are not showing up on the sendportal. I do have notifications on horizon but on displaying on sendportal.
