### ISSUE TITLE
The mails are not sent (scheduled or not except sending in test mode)

### ISSUE THREAD

**Issue by Yuniverse-tech** [mettle/sendportal#58]
I reopen this ticket because the problem still persists despite a configuration with horizon and supervisor. All the scheduled sendings do not work and the status `queue` is still there and no message received! Sending in test mode works wonderfully against. It seems to me that it has to be done via the terminal, no job or schedule is in place except the `CampaignDispatchCommand` class to be executed manually from the terminal. #52 

Even with these settings from the campaigns. The campaign is not sent and therefore not received

![Capture du 2020-07-23 03-03-49](https://user-images.githubusercontent.com/56940294/88243665-68df2480-cc91-11ea-92c5-ffe9ab4926db.png)

**Comment by mpixelz** [comment]
Hi,
im having the same issue as above.. im using redis with horizon. 
Horizon shows active.. already added horizon daemon on laravel forge. test email sent successfully but campaign stuck at queued.

**Comment by mpixelz** [comment]
UPDATE: 
i ran `php artisan schedule:run` on my terminal and the queue started and sent successfully.. As per my understanding when using redis this should not have happened.
But now when i look at horizon log this is what i got:
```
{
class: "Sendportal\Base\Listeners\MessageDispatchHandler",
method: "handle",
data: [
{
message: {
class: "Sendportal\Base\Models\Message",
id: 1,
relations: [
],
connection: "mysql"
},
socket: null
}
],
tries: null,
retryAfter: null,
timeoutAt: null,
timeout: null,
job: null
}
```

why is it not taking redis connection? i checked my .env file and i do have redis connection setup there. can someone shed some light on this?

**Comment by JonoB** [comment]
You MUST set up a cron job to dispatch your campaigns automatically. See Cron Jobs in https://sendportal.io/docs/getting-started/configuration-and-setup

If you are using SES, please make sure that you update to the latest `sendportal-core` package (`v1.0.4`)

**Comment by mpixelz** [comment]
> You MUST set up a cron job to dispatch your campaigns automatically. See Cron Jobs in https://sendportal.io/docs/getting-started/configuration-and-setup
> 
> If you are using SES, please make sure that you update to the latest `sendportal-core` package (`v1.0.4`)

Cron still need to be run even if using redis?

**Comment by JonoB** [comment]
Yes, the cron is used to run the `DispatchCampaign` command, which pushes the individual messages into a queue.

**Comment by Yuniverse-tech** [comment]
@JonoB But what is the use of "horizon" then. In my case, I use horizon with supervisor, this config normally replaces the default cron of laravel "php artisan schedule: run", it avoids launching it manually. How can you do this with Redis, Horizon and Supervisor? I am using this setup with another project in which it works but does not work with the sendportal project.

**Comment by JonoB** [comment]
It works something like this:

- Campaigns are in draft mode have a status_id = 1
- When you click send, this updates campaigns.status_id = 2
- There is a cron job that runs every minute and invokes `CampaignDispatchCommand`
- `CampaignDispatchCommand` loads all campaigns where status_id = 2 and calls `CapaignDispatchService`
- `CampaignDispatchService` creates individual messages for each campaign - the messages are dispatched via queue (in your case Horizon)

So, at the moment you need both cron and queue for a campaign to work.

We are considering moving the command to a queue item instead, but this is something for the future. 

Hope that helps!

**Comment by Yuniverse-tech** [comment]
OK OK, understood! I have a suggestion for all those who are in the same situation as me `Redis - Horizon - Supervisor` therefore who do not use or who do not want to manually use `php artisan schedule:run`. Add a schedule directly in `\App\Console\Kernel` which runs the command found in `CampaignDispatchCommand` every minute. It should look something like: `$schedule->command('sp:campaigns:dispatch')->everyMinutes();`. All the while knowing that your `Redis - Horizon and supervisor` configuration is successful.

**Comment by JonoB** [comment]
@Yuniverse-tech The schedule already exists: https://github.com/mettle/sendportal-core/blob/master/src/Console/Kernel.php

You only need to add a cron job to run every minute, and every thing should work fine :rocket:

**Comment by Yuniverse-tech** [comment]
@JonoB Ok but when the task is set here https://github.com/mettle/sendportal-core/blob/master/src/Console/Kernel.php my config can't run the command but when I recreate it again in the root project ie here "https://github.com/mettle/sendportal" directly, everything works fine! I would use this operation for now. Thank you !
