### ISSUE TITLE
Amazon SNS open/click tracking not working.

### ISSUE THREAD

**Issue by mpixelz** [mettle/sendportal#59]
Hi,
I was able to setup the amazon ses to send out the emails.. after some trouble was able to setup cron job as well (using kernal.php schedule commands).. BUT im not getting the tracking information.. The webhooks appear to be working correctly as well, and all the SNS notifications are received based on the log entries on horizon as well.. But they are not being updated on the sendportal reports.
The campaigns do have `is_open_tracking` and `is_click_tracking` enabled but doesnt seem to be working. Any ideas?
all the help is much appreciated.
Thanks.

P.S the issue is very similar to this mentioned issue.. 
#55

**Comment by JonoB** [comment]
Is `sendportal-core` on `v1.0.4` ?

**Comment by mpixelz** [comment]
Hi, yes composer.lock file was not being submitted, so server was still using older version. got it fixed.. thanks.

**Comment by recoverjp** [comment]
Search for the HandleSesWebhook.php file and add the following to the first line of the class:

/** @var string */
public $queue = 'sendportal-webhook-process';
