### ISSUE TITLE
Confirm opt-in

### ISSUE THREAD

**Issue by Cannonb4ll** [mettle/sendportal#65]
Hi!

I might of missed it maybe, but I fail to seem to find a configuration option for subscribers to confirm them selfs.

By law, it is officially required for people to confirm their opt-in via email after the first submission.

Is this available in sendportal?

**Comment by JonoB** [comment]
Hey @Cannonb4ll, at the moment we're assuming that the opt-in has already been performed when you add a subscriber to SendPortal. We may add this functionality at some point (or gladly accept a PR).

**Comment by DominikGeimer** [comment]
@Cannonb4ll I handle the opt-in with a subscriber table and I am sending confirmation emails with Laravel [Signed URLs]((https://laravel.com/docs/7.x/urls#signed-urls)). When a user clicks this URL I send an API call to Sendportal to create the subscriber and delete the email from my subscriber table. 

But I would be great if we could at least get and update the sendportal subscriber status via the api.

Offtopic: @Cannonb4ll I love ploi.io and I am a happy customer :-)

**Comment by Cannonb4ll** [comment]
@DominikGeimer Thanks! 

So I recon you included the sendportal-core into your own Laravel app and did the signed URL stuff in there?

Offtopic: Thanks mate, much appreciated! 💙

**Comment by DominikGeimer** [comment]
> @DominikGeimer Thanks!
> 
> So I recon you included the sendportal-core into your own Laravel app and did the signed URL stuff in there?
> 

No. The apps are entirely separated. 

I do the following in my laravel app and I did not include anything from sendportal.

When a visitor signs up for the newsletter, I save his email address in a subscriber table and send an email with a signed URL link. When the visitor clicks this link as a signup confirmation, I grab the email and make an API call to sendportal to create the user inside sendportal. After that, I return a signup confirmation view.

**Comment by Cannonb4ll** [comment]
Ah I see, a separate Laravel application that communicates with your sendportal environment. That makes sense, thanks, I will create this as well like this.

**Comment by Sepremex** [comment]
Wait, let me see if I got this right, one Laravel app for your normal website and another Laravel install for SendPortal, on the Laravel website you handle the Opt-In if user clicks or register via web form then the normal website handles the "Opt-in" then use the API just to register that user in the SendPortal App... is that correct?

**Comment by JonoB** [comment]
> Wait, let me see if I got this right, one Laravel app for your normal website and another Laravel install for SendPortal, on the Laravel website you handle the Opt-In if user clicks or register via web form then the normal website handles the "Opt-in" then use the API just to register that user in the SendPortal App... is that correct?

Yep! We may introduce opt-in functionality in the future.

**Comment by krognome** [comment]
No way man you can do it all on 1 Laravel install. I changed the code a small amount to have subscribers bound to an individual user etc.
