### ISSUE TITLE
Subscribers import not working

### ISSUE THREAD

**Issue by lucaros97** [mettle/sendportal#67]
Hello,
I'm trying to import a list of subscribers manually from a csv file but it's not working.
I think i've set the csv correctly but the requests end "successfully" with 0 subscribers imported.
![image](https://user-images.githubusercontent.com/8333004/88892596-4fb41600-d245-11ea-9986-9184dc369907.png)

My csv file:
![image](https://user-images.githubusercontent.com/8333004/88892683-7ffbb480-d245-11ea-8a3e-6ef4ead4664b.png)

I also tried without the id column

Thanks!

**Comment by mauricius** [comment]
Hi @lucaros97 can you post the raw format of your csv file?

The following works for me
```csv
id,email,first_name,last_name
,test@test.it,Luca,Rossi
```

**Comment by lucaros97** [comment]
Hi,
My fault. I was using a csv with ";" as delimiter instead of ","

Thanks!
