### ISSUE TITLE
Page breaks when opening the action menu on the "Completed Campaigns" widget in the dashboard

### ISSUE THREAD

**Issue by MathiasOliveira** [mettle/sendportal#69]
#### Issue description

After opening the actions menu on the "Completed Campaigns" in the dashboard the page breaks

#### Steps to reproduce the issue

1.  Have a completed campaign
2. Click on the three dots in the action column

#### What's the expected result?

- The menu to open beside the three dots

#### What's the actual result?

- The whole div spands above what its suppose to and is pushed down beneath the sidebar.

#### Additional details / screenshot

- Before clicking:
![Before clicking](https://i.imgur.com/WkDQb6D.png)
- After clicking (Printscreen of the whole page):
![After clicking](https://i.imgur.com/idDxGBo.png)

**Comment by joshuafranks** [comment]
Hey @MathiasOliveira,

I wasn't able to reproduce this when testing in Chrome, Firefox and Safari. What browser were you using? Are you on the latest version of [mettle/sendportal-core](https://github.com/mettle/sendportal-core/releases/tag/v1.0.6)?

**Comment by MathiasOliveira** [comment]
I am using Chrome 84.0.4147.125,
and my composer.json says i am using mettle/sendportal-core ^1.0.
I can't reproduce the bug either, now that i have more campaigns and subscribers showing in the dashboard.

**Comment by JonoB** [comment]
Thanks @MathiasOliveira - we'll close this one down in the meantime. If it happens again, please let us know!
