### ISSUE TITLE
Segment deattachs all subscribers after being edited

### ISSUE THREAD

**Issue by MathiasOliveira** [mettle/sendportal#70]
#### Issue description
If a segment is edited and it has subscribers any edit will make it deattach all subscribers to that segment.

#### Steps to reproduce the issue

1. Create a segment and add a subscriber
2. Edit the same segment

#### What's the expected result?

- Either for the segment to keep all of its subscriber or a warning saying that any edits to a segment will make all subscribers to not be attached to the edited segment.

#### What's the actual result?

- All subscribers attach to said segment are deattach to the edited segment.

#### Additional details / screenshot

- Before editing:
![Before Editing](https://i.imgur.com/YyVRtoJ.png)
- After editing:
![After Editing](https://i.imgur.com/W95msfq.png)
- Sending options in a campaign:
![After Editing](https://i.imgur.com/fgoqSf0.png)

**Comment by willselby** [comment]
Hey @MathiasOliveira, thanks for pointing this out! This has been fixed in v1.0.7.
