### ISSUE TITLE
AWS SES 400 Bad Request: ConfigurationSetDoesNotExist

### ISSUE THREAD

**Issue by lucaros97** [mettle/sendportal#75]
Trying to send a test mail before sending the campaign i get this error:
![image](https://user-images.githubusercontent.com/8333004/91059918-9883a280-e62a-11ea-889d-13430ea9174a.png)

Some times ago the configuration was working correctly!

Any hint?

**Comment by JonoB** [comment]
You'll need to check your AWS settings and permissions. See https://sendportal.io/docs/email-services/aws

Did you perhaps change your IAM user at some point?

**Comment by lucaros97** [comment]
Missed that! Now it's working, thanks!
