### ISSUE TITLE
Send automatically not working

### ISSUE THREAD

**Issue by lucaros97** [mettle/sendportal#78]
When trying to send automatically a campaign instead of "queue draft", mails are not sent.
Everythings else works. I'm using AWS SES and when it's set to "queue draft" messages appear in the draft section and i'm able to send them manually.
When it's set to "send automatically", messages appear in the messages table in the database but no one are sent.

Any hint?

**Comment by mauricius** [comment]
You probably mean SQS, right?

SQS is not entirely supported out of the box, in fact is not even mentioned in the [documentation](https://sendportal.io/docs/getting-started/configuration-and-setup#additional-configuration), but you can use it anyway. Just make sure to give the correct names to your SQS queues:

- `sendportal-message-dispatch` for the queue that dispatches the messages
- `sendportal-webhook-process` for the queue that handles webhooks

**Comment by lucaros97** [comment]
No, I'm not using Amazon SQS. I'm just using "Database" as the queue system, and Amazon SES as email service

**Comment by JonoB** [comment]
Hey @lucaros97, have you set a cron job and/or run your queue workers?

Please see https://sendportal.io/docs/getting-started/configuration-and-setup#additional-configuration for more information.

**Comment by lucaros97** [comment]
Yes, a cron job has been setup on the server and also queue workers are running

**Comment by JonoB** [comment]
Can you please check the status of your campaign. This is in the `campaigns` table in the `status_id` field.

- 1 = draft
- 2 = queued
- 3 = processing
- 4 = completed

The campaign will only be dispatched if its in `queued` status. If necessary, manually update the `status_id` to `2` and see what happens.

Also, make sure that the `campaigns.scheduled_at` date is in the past.

Have you checked your log files? When a campaign starts dispatching, then your should get a `Dispatching campaigns count=[1]` in your log file.

**Comment by lucaros97** [comment]
The campaign obviously before dispatch it's in `queued` status. Also tried to update the status to 2 manually but nothing works.
Tried also with the default "sync" queue system and now i'm using Redis with Horizon and both works

**Comment by JonoB** [comment]
So its working with sync and redis, but not with database?

**Comment by lucaros97** [comment]
Exactly

**Comment by JonoB** [comment]
Have you run the following commands?
```
php artisan queue:table
php artisan migrate
```

**Comment by lucaros97** [comment]
Yes, all the command and tasks to configure th environment were made

**Comment by LeonBuchner** [comment]
I have the same error. All campgaigns which are queued will not get send when I run `php artisan schedule:run`.
The status in the database will change to "sent" but when I check the campaign report it will have 0 Recipients.
 "Messages" from the menu is also empty.

Any solution?

**Comment by lucaros97** [comment]
Didn't find any solutions for the database queue system. I moved to Horizon + Redis

**Comment by mauricius** [comment]
@LeonBuchner @lucaros97 we're updating the documentation because it was not completely exhaustive on this topic.

Sendportal is configured with two queue names, one for dispatching campaign messages `sendportal-message-dispatch` and the other one for handling webhooks `sendportal-webhook-process`.

You have to make sure to run the queue worker with the appropriate queue name, otherwise it's going to process only jobs from the `default` queue.

```
php artisan queue:work --queue=sendportal-message-dispatch
php artisan queue:work --queue=sendportal-webhook-process
```

**Comment by LeonBuchner** [comment]
I just did a reinstall today to see if its working and now it works when I run 
```php artisan schedule:run```
