### ISSUE TITLE
editing this repo

### ISSUE THREAD

**Issue by Silassiai** [mettle/sendportal#85]
Hi,

Just installed and configered the application.
It works very nice! I wonder what the idea is behind the fact all sendportal code is in the vendor package.

What is the best approach if i want to add or change pages and how to deal when this repo is updated?

Is there a build in tracking in this sendportal package or is the tracking done by the services?

**Comment by JonoB** [comment]
Hi @Silassiai 

We'll be releasing SendPortal as a package soon, so you can install in your own project. Watch this space!

Tracking is all handled by external services.
