### ISSUE TITLE
Administrator change password

### ISSUE THREAD

**Issue by foongpon** [mettle/sendportal#87]
Hi,

Is there a way for administrator to change password via UI? 
What is the hashing method for password so that I can reset password via mysql command line?
I have tried MD5 it didnt work.

**Comment by foongpon** [comment]
Found it. BCrypt hash. I used htpasswd in linux to reset password. 
However it would be nice to have an interface for user to reset password inside sendportal instead of using "Forgot Your Password"
Thank you.

**Comment by JonoB** [comment]
I'll re-open this issue as its something we will want to add in the future.

**Comment by foongpon** [comment]
Good one! Looking forward to it. Thank you.

**Comment by JonoB** [comment]
This has been implemented in v2.0.1: https://github.com/mettle/sendportal/pull/118
