### ISSUE TITLE
production.INFO: Message is not valid

### ISSUE THREAD

**Issue by daniyals14** [mettle/sendportal#90]
Im trying to send out a campaign through sending draft using SES and im getting this error on laravel log on version 1.0.9, any help with this please?

I downgraded to 1.0.7 and it works fine

**Comment by JonoB** [comment]
@daniyals14 - Can you share the error that you're getting?

**Comment by daniyals14** [comment]
production.INFO: Message is not valid

**Comment by JonoB** [comment]
@daniyals14 - thanks, but we can't help with just that information. We'll need more info to help more.

**Comment by way2innovations** [comment]
@JonoB 

I have the same issue after update to sendportal-core 1.0.9

Check it on
1. sendportal-core 1.0.9
2. Mailgun

**Comment by platinumwizard** [comment]
@JonoB
I have the same issue after update to sendportal-core 1.0.9.

When I launch any campaign (using template, no matter right now, or draft), messages aren't sent. 
In log-file for each message: "Message is not valid".

Check it, please, on:
1. sendportal-core 1.0.9
2. Mailgun

**Comment by daniyals14** [comment]
@JonoB That is the only log message on the Laravel log, the test email goes out fine when setting up the campaign, the test email when adding the SES mail sending also goes fine but when campaign is actually sent out, only this message is logged, nothing else.

**Comment by platinumwizard** [comment]
> @JonoB That is the only log message on the Laravel log, the test email goes out fine when setting up the campaign, the test email when adding the SES mail sending also goes fine but when campaign is actually sent out, only this message is logged, nothing else.

I have totally the same situation

**Comment by JonoB** [comment]
OK, thanks. Will take a look in a bit

**Comment by JonoB** [comment]
[v1.0.10](https://github.com/mettle/sendportal-core/releases/tag/v1.0.10) has been tagged that fixes this bug. Please upgrade!
