### ISSUE TITLE
mail sending issues 

### ISSUE THREAD

**Issue by nagaraj32** [mettle/sendportal#94]
Response: Error executing "SendEmail" on "https://email.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://email.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> <Error> <Type>Sender</Type> <Code>MessageReje (truncated...) MessageRejected (client): Email address is not verified. The following identities failed the check in region US-WEST-2: Sendportal <nagaraj@datafindsolution.com> - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> <Error> <Type>Sender</Type> <Code>MessageRejected</Code> <Message>Email address is not verified. The following identities failed the check in region US-WEST-2: Sendportal &lt;nagaraj@datafindsolution.com&gt;</Message> </Error> <RequestId>158e381e-f178-4a80-903b-e21d6e67669c</RequestId> </ErrorResponse>

**Comment by ediblemanager** [comment]
@nagaraj32 you'll need to configure the email address for validation in SES. https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-set-up.html should help get you started.

**Comment by nagaraj32** [comment]
thanks for your response, i send same domain test mail working , send different domain error, please help me that

**Comment by JonoB** [comment]
Please read our help documentation _very carefully_ - it contains all the steps https://sendportal.io/docs/email-services/aws
