### ISSUE TITLE
Adding SES service with env credentials

### ISSUE THREAD

**Issue by Flynsarmy** [mettle/sendportal#97]
Why are AWS access/secret/region required fields when adding an SES email service in the browser backend if those values have already been entered into .env as per [the documentation](https://sendportal.io/docs/getting-started/configuration-and-setup#user-content-ses).

**Comment by JonoB** [comment]
There are 2 separate email configs - one for handling internal email (team invites, forgot password, etc, and one for handling campaigns.

The config vars in the `.env` file are for internal email, the `Email Services` is for campaigns.

See `User Management Email` section at https://sendportal.io/docs/getting-started/configuration-and-setup#manual-configuration
