### ISSUE TITLE
A "How to" of adding  SMTP Services in sendportal 

### ISSUE THREAD

**Issue by rzafiamy** [mettle/sendportal#98]
I decide to patch my sendportal-core instance to handle smtp service. 
Feel free to test this solution :  https://github.com/rzafiamy/sendportal-smtp

**Comment by JonoB** [comment]
This has been implemented in v2.0.1: https://github.com/mettle/sendportal-core/pull/112

Docs: https://sendportal.io/docs/v2/email-services/smtp
